# .github/workflows/ci.yml
name: CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: cards/backend/package-lock.json

      - name: Install (backend)
        working-directory: cards/backend
        run: npm ci

      - name: Run tests (backend)
        working-directory: cards/backend
        env:
          NODE_ENV: test
          JWT_SECRET: test-secret
          SENDGRID_API_KEY: dummy
          EMAIL_USER: test@example.com
        run: npm run test:coverage   # uses your cross-env jest script

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: cards/backend/coverage
          if-no-files-found: ignore
